### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'new_context' after update to 0.0.11 version

### ISSUE THREAD

**Issue by akozyreva** [microsoft/playwright-pytest#38]
Hi!
I use following versions
```
playwright==1.8.0a1
pytest-playwright==0.0.11
```
When I try to run this simple test
```
import pytest

@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "viewport": {
            "width": 1920,
            "height": 1080,
        }
    }


def test_3(page):
    page.goto("https://github.com/")
 ```
 I see the following errors
 ```
 
test_3.py::test_3 ERROR                                                                                                      [100%]
test_3.py::test_3 ERROR                                                                                                      [100%]

============================================================== ERRORS ==============================================================
_____________________________________________________ ERROR at setup of test_3 _____________________________________________________

browser = <selenium.webdriver.chrome.webdriver.WebDriver (session="a04299d9467e720629597b732e376de3")>
browser_context_args = {'viewport': {'height': 1080, 'width': 1920}}

    @pytest.fixture
    def context(
        browser: Browser, browser_context_args: Dict
    ) -> Generator[BrowserContext, None, None]:
>       context = browser.new_context(**browser_context_args)
E       AttributeError: 'WebDriver' object has no attribute 'new_context'

../../.venv/lib/python3.9/site-packages/pytest_playwright/pytest_playwright.py:128: AttributeError
------------------------------------------------------ Captured stdout setup -------------------------------------------------------
['--start-maximized', 'window-size=2560,1440']
___________________________________________________ ERROR at teardown of test_3 ____________________________________________________

request = <SubRequest 'browser' for <Function test_3>>

    @pytest.fixture()
    def browser(request):
        browser = None
        options = get_browser_options(request)
        # check, if we try to pass arguments
        if hasattr(request, 'param'):
            # parse param
            params = request.param.split(", ")
            print(params)
            if params[0] == "experimenatal_option":
                print(params[1], params[2], params[3])
                options.add_experimental_option(params[1], {params[2]: params[3]})
        # options.add_experimental_option("w3c", False)
        # add for allowing to see network logs
        caps = DesiredCapabilities.CHROME
        #as per latest docs
        caps['goog:loggingPrefs'] = {'performance': 'ALL'}
        browser = webdriver.Chrome(desired_capabilities=caps, options=options)
        browser.implicitly_wait(5)
        yield browser
        # Do teardown (this code will be executed after each test):
        #print(request.node.rep_call)
        # to do - if broken, pls make a screenshot
>       if request.node.rep_call.failed:
E       AttributeError: 'Function' object has no attribute 'rep_call'

../../config/init_browser.py:55: AttributeError
------------------------------------------------------ Captured stdout setup -------------------------------------------------------
['--start-maximized', 'window-size=2560,1440']
===================================================== short test summary info ======================================================
ERROR test_3.py::test_3 - AttributeError: 'WebDriver' object has no attribute 'new_context'
ERROR test_3.py::test_3 - AttributeError: 'Function' object has no attribute 'rep_call'
```

**Comment by mxschmitt** [comment]
Hi, seems like related to #14. It's not compatible with Selenium pytest plugin.

**Comment by akozyreva** [comment]
Hi, I don't use Selenium pytest plugin. it's the list of my packages.
```
pip list
Package               Version
--------------------- ---------
allure-pytest         2.8.16
allure-python-commons 2.8.16
apipkg                1.5
astroid               2.4.2
attrs                 19.3.0
certifi               2020.12.5
chardet               4.0.0
execnet               1.7.1
greenlet              1.0.0
idna                  2.10
importlib-metadata    1.6.0
iniconfig             1.1.1
isort                 4.3.21
lazy-object-proxy     1.4.3
mccabe                0.6.1
more-itertools        8.3.0
packaging             20.4
pip                   20.2.4
playwright            1.8.0a1
pluggy                0.13.1
py                    1.8.2
pycodestyle           2.6.0
pyee                  8.1.0
pylint                2.5.3
pyparsing             2.4.7
pytest                6.1.1
pytest-base-url       1.4.2
pytest-check          0.3.9
pytest-dependency     0.5.1
pytest-forked         1.1.3
pytest-metadata       1.9.0
pytest-playwright     0.0.11
pytest-xdist          2.1.0
requests              2.25.1
selenium              3.141.0
setuptools            50.3.2
six                   1.15.0
termcolor             1.1.0
toml                  0.10.1
typed-ast             1.4.1
typing-extensions     3.7.4.3
urllib3               1.25.9
wcwidth               0.1.9
wheel                 0.35.1
wrapt                 1.12.1
zipp                  3.1.0
```

**Comment by akozyreva** [comment]
@mxschmitt I deleted `selenium` package and error is gone. Could you please update documentation? I try to migrate from selenium to playwright, and it was surprise for me, that there're not compatible.

**Comment by mxschmitt** [comment]
@akozyreva I tried to understand the underlying problem. It seems not that Selenium is automatically adding a fixture with the name `browser` to pytest. Did you maybe have a custom `conftest.py` where you had a `def browser()` fixture defined?

**Comment by akozyreva** [comment]
Yes, you're right. I deleted it and now everything works fine!
